version: '3'

services:
  wildfly:
    environment:
      - TZ=Europe/Stockholm
    build:
      context: ./src/wildfly
      dockerfile: Dockerfile-wildfly
    ports:
      - 8080:8080
      - 9990:9990

  postgres:
    environment:
      - TZ=Europe/Stockholm
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=gameon-xdb
    image: postgres:12.4-alpine
    ports:
      - 5432:5432

  wildfly-config:
    environment:
      - TZ=Europe/Stockholm
    build:
      context: src/wildfly-config
      dockerfile: Dockerfile-wildfly-config
