version: '3'

services:
  wildfly:
    environment:
      - TZ=Europe/Stockholm
    build:
      context: ./src/wildfly
      dockerfile: Dockerfile-wildfly
    volumes:
      - C:\\WS\\docker\\volumes\\gameon\\wildfly\\wildfly-standalone-deployments:/opt/jboss/wildfly/standalone/deployments
    ports:
      - 8088:8080
      - 9990:9990


  postgres:
    image: postgres:12.4-alpine
    environment:
      - TZ=Europe/Stockholm
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=gameon-xdb
    volumes:
      - C:\\WS\\docker\\volumes\\gameon\\postgresql\\postgresql-data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  wildfly-config:
    environment:
      - TZ=Europe/Stockholm
    build:
      context: src/wildfly-config
      dockerfile: Dockerfile-wildfly-config
