services:
  postgres:
    image: postgres:12.4-alpine
    environment:
      - TZ=Europe/Stockholm
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=gameon-xdb
    volumes:
      - C:\\WS\\docker\\volumes\\gameon\\postgresql\\postgresql-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
