services:
  wildfly:
    environment:
      - TZ=Europe/Stockholm
    build:
      context: ./src/wildfly
      dockerfile: Dockerfile-wildfly
    volumes:
      - C:\\WS\\docker\\volumes\\gameon\\wildfly\\wildfly-standalone-deployments:/opt/jboss/wildfly/standalone/deployments
    ports:
      - 8088:8080
      - 9990:9990


  postgres:
    extends:
      file: docker-compose-postgresql.yml
      service: postgres

  wildfly-config:
    environment:
      - TZ=Europe/Stockholm
    build:
      context: src/wildfly-config
      dockerfile: Dockerfile-wildfly-config
