version: '3'

services:
  wildfly_gameon:
    build:
      context: ./src/wildfly
      dockerfile: Dockerfile-wildfly
    ports:
      - 8080:8080
      - 9990:9990
#    env_file:
#      - ./src/tomee/catalinaopts.env

  postgres_gameon:
    image: postgres:12.4-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=gameon-xdb

