@startuml
skinparam componentStyle uml2


legend top
Components
end legend


component CLI

node App {
    component Batch


    interface DataProducerControllerInterface as "REST"

    component DataProducerController {
        component JaxRsClient
        component TopicProducer
    }


    queue Topic

    component DataConsumerController {
        component TopicConsumer
        component Repository
    }
}

interface SportsDataInterface


database Database

Batch --> DataProducerController
CLI --> DataProducerControllerInterface
DataProducerControllerInterface --> DataProducerController

JaxRsClient --> SportsDataInterface

TopicProducer --> Topic

Topic --> TopicConsumer

Repository --> Database

@enduml
