@startuml
skinparam componentStyle uml2

legend top
Components
end legend

component CLI

node App {
    component Batch

    interface DataProducerControllerInterface as "REST"

    component DataProducerController {
        component Service as ProducerService
        component RestClient
        component MessageProducer
    }


    queue Queue

    component DataConsumerController {
        component Service as ConsumerService
        component MessageConsumer
        component Repository
    }
}

interface ExternalDataInterface

database Database

Batch --> ProducerService
CLI --> DataProducerControllerInterface
DataProducerControllerInterface --> ProducerService

ProducerService --> RestClient
ProducerService --> MessageProducer
RestClient --> ExternalDataInterface
MessageProducer --> Queue

Queue --> MessageConsumer
MessageConsumer --> ConsumerService
ConsumerService --> Repository
Repository --> Database

@enduml
