spring:
  main:
    banner-mode: off;
  
  datasource:
    driver-class-name: org.hsqldb.jdbc.JDBCDriver
    url: jdbc:hsqldb:jdbc:hsqldb:mem
    username: sa
    password:

  liquibase:
    change-log: liquibase/master.xml
